"""Tool scaffolder — draft-scaffold generator for missing capabilities.

When the executor encounters an ``UnknownCapabilityError`` (a capability that
has no handler registered in :class:`~freetalon.orchestrator.tool_registry.ToolRegistry`),
this module writes a *draft* Python stub to a quarantined directory so a human
can review, implement, and register it.

Security invariants (see ADR 0000, Task 2.2):

- The generated file is **never** imported, executed, or registered at runtime.
- The quarantine directory is **never** placed on ``sys.path``.
- Generation and execution are separated by a human review and a commit.
- Capability names are validated against :data:`~freetalon.security.SAFE_TEXT_PATTERN`
  and path-traversal sequences are rejected before any file-system operation.
- If an optional ``codegen_backend`` callable is injected, its only effect is
  producing the file *content* string; default is a static template (no LLM,
  no network).

Typical usage from the executor::

    scaffolder = ToolScaffolder(base_dir=Path("generated/proposed_tools"))
    proposal = scaffolder.propose("my_missing_cap", node_inputs={"key": "value"})
    # proposal.path  — where the draft was written
    # proposal.content_hash — SHA-256 hex digest of the file content
"""

from __future__ import annotations

import hashlib
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

# Mirror the SAFE_TEXT_PATTERN from freetalon.security but restricted further:
# capability names used as directory components must be alphanumeric + underscores
# only.  No spaces, slashes, dots, or other path-meaningful characters.
_CAPABILITY_PATTERN = re.compile(r"^[a-zA-Z0-9_]{1,64}$")

# Default quarantine root, relative to the repository root.  Callers (and tests)
# should override via the ``base_dir`` constructor argument.
_DEFAULT_BASE_DIR = Path("generated") / "proposed_tools"

# README template — tells a human reviewer exactly what to do.
_README_TEMPLATE = textwrap.dedent("""\
    # Proposed tool: `{capability}`

    This directory was generated automatically by FreeTalon's `ToolScaffolder`
    because the capability `{capability}` was required by an execution plan but
    had no registered handler.

    ## How to review and register this tool

    1. Open `handler.py` and implement the `handle` function.
    2. Ensure the handler accepts a `dict` of inputs and returns a `dict` of
       outputs (matching the `AsyncHandler` type alias in `tool_registry.py`).
    3. Write tests for the handler in `tests/`.
    4. Register the handler in the appropriate registry setup module:

           registry.register("{capability}", handler.handle)

    5. Open a pull request.  The plan node will remain in `NEEDS_TOOL` status
       until the capability is registered and the plan is re-submitted.

    **Do NOT modify `handler.py` in-place and restart the process.**
    The executor resolves capabilities **only** from the `ToolRegistry` allowlist.
    A generated scaffold is inert until a human reviews it, merges it, and it
    is explicitly registered.

    ---
    *Generated by FreeTalon ToolScaffolder (ADR 0000 Task 2.2).*
    *Runtime code-generation-and-execution was deliberately NOT implemented per
    security review — generation and execution are separated by a human and a
    commit.*
""")

# Handler stub template.
_HANDLER_TEMPLATE = textwrap.dedent("""\
    \"\"\"Draft scaffold for capability: {capability}

    AUTO-GENERATED — DO NOT EXECUTE BEFORE HUMAN REVIEW.

    This file was produced by FreeTalon's ToolScaffolder (ADR 0000 Task 2.2).
    It is intentionally incomplete.  A human must implement the `handle`
    function, review the result, and register it with:

        registry.register("{capability}", handle)

    See the accompanying README.md for full instructions.
    \"\"\"

    from __future__ import annotations

    # TODO: import the libraries you need here.


    async def handle(inputs: dict) -> dict:
        \"\"\"Handle the '{capability}' capability.

        Parameters
        ----------
        inputs:
            Dictionary of node inputs passed by the executor.

        Returns
        -------
        dict
            Output dictionary consumed by downstream nodes.
        \"\"\"
        # TODO: implement this handler.
        raise NotImplementedError(
            "The '{capability}' handler scaffold has not been implemented yet.  "
            "Edit this file, review it, and register it with the ToolRegistry."
        )
""")


@dataclass(frozen=True)
class ScaffoldProposal:
    """Metadata about a proposed scaffold file.

    Attributes
    ----------
    capability:
        The capability name that was missing.
    path:
        Absolute path to the generated ``handler.py`` stub.
    content_hash:
        SHA-256 hex digest of the file content (for audit logging).
    """

    capability: str
    path: Path
    content_hash: str


class CapabilityNameError(ValueError):
    """Raised when a capability name fails validation (path traversal, unsafe chars)."""


class ToolScaffolder:
    """Generates draft tool scaffolds for missing capabilities.

    Parameters
    ----------
    base_dir:
        Root directory for generated scaffolds.  Each capability gets its own
        sub-directory ``<base_dir>/<capability>/``.  Defaults to
        ``generated/proposed_tools`` (relative to the current working directory).
    codegen_backend:
        Optional injectable callable with signature
        ``(capability: str, inputs: dict) -> str`` that returns the content of
        ``handler.py``.  Defaults to a static template (no LLM, no network).
        If provided, its *only* effect must be returning a content string — it
        must not import, exec, or register anything.
    """

    def __init__(
        self,
        base_dir: Path | None = None,
        codegen_backend: Callable[[str, dict[str, Any]], str] | None = None,
    ) -> None:
        self._base_dir: Path = Path(base_dir) if base_dir is not None else _DEFAULT_BASE_DIR
        self._codegen_backend = codegen_backend
        self._assert_not_on_sys_path()

    # ── Public API ────────────────────────────────────────────────────────

    def propose(
        self,
        capability: str,
        node_inputs: dict[str, Any] | None = None,
    ) -> ScaffoldProposal:
        """Generate a draft scaffold for *capability* and write it to disk.

        Parameters
        ----------
        capability:
            The missing capability name.  Must match ``^[a-zA-Z0-9_]{1,64}$``.
        node_inputs:
            The inputs dict from the plan node (used only for content generation
            context; never written to the scaffold unredacted).

        Returns
        -------
        ScaffoldProposal
            Metadata describing the written file.

        Raises
        ------
        CapabilityNameError
            If *capability* fails validation (unsafe characters, path traversal).
        """
        self._validate_capability(capability)
        self._assert_not_on_sys_path()

        inputs = node_inputs or {}
        cap_dir = self._base_dir / capability
        cap_dir.mkdir(parents=True, exist_ok=True)

        handler_path = cap_dir / "handler.py"
        readme_path = cap_dir / "README.md"

        # Generate handler content (static template or injected backend).
        if self._codegen_backend is not None:
            handler_content = self._codegen_backend(capability, inputs)
        else:
            handler_content = _HANDLER_TEMPLATE.format(capability=capability)

        readme_content = _README_TEMPLATE.format(capability=capability)

        handler_path.write_text(handler_content, encoding="utf-8")
        readme_path.write_text(readme_content, encoding="utf-8")

        content_hash = hashlib.sha256(handler_content.encode("utf-8")).hexdigest()

        return ScaffoldProposal(
            capability=capability,
            path=handler_path.resolve(),
            content_hash=content_hash,
        )

    # ── Internal helpers ──────────────────────────────────────────────────

    @staticmethod
    def _validate_capability(capability: str) -> None:
        """Reject capability names that could cause path traversal or injection.

        Raises
        ------
        CapabilityNameError
            If the name does not match ``^[a-zA-Z0-9_]{1,64}$`` or contains
            path-traversal sequences.
        """
        if not isinstance(capability, str):
            raise CapabilityNameError(
                f"Capability name must be a str, got {type(capability).__name__!r}."
            )
        # Explicit traversal checks (belt-and-suspenders in addition to the pattern).
        if ".." in capability or "/" in capability or "\\" in capability or "\x00" in capability:
            raise CapabilityNameError(
                f"Capability name {capability!r} contains path-traversal sequences."
            )
        if not _CAPABILITY_PATTERN.fullmatch(capability):
            raise CapabilityNameError(
                f"Capability name {capability!r} is invalid.  "
                "Only alphanumeric characters and underscores are allowed (1–64 chars)."
            )

    def _assert_not_on_sys_path(self) -> None:
        """Assert that the quarantine base directory is not on ``sys.path``.

        This is a hard security invariant: generated scaffolds must never be
        importable at runtime.
        """
        resolved = self._base_dir.resolve()
        for entry in sys.path:
            try:
                entry_resolved = Path(entry).resolve()
            except Exception:  # noqa: BLE001
                continue
            if entry_resolved == resolved or resolved.is_relative_to(entry_resolved):
                raise AssertionError(
                    f"Security violation: the scaffold quarantine directory "
                    f"{resolved!s} is on sys.path (via {entry!r}).  "
                    "Generated scaffolds must never be auto-importable."
                )
